"""Add reason field to Owner model

Revision ID: 0acff9827def
Revises: e0719704fc80
Create Date: 2025-06-02 13:14:30.452333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0acff9827def'
down_revision = 'e0719704fc80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.Text(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('personal_id',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.alter_column('personal_id',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=12),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=12),
               existing_nullable=True)
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('reason')

    # ### end Alembic commands ###
