"""add social usernames to renter

Revision ID: 89f02cf4884e
Revises: deb62770d2cb
Create Date: 2025-06-08 20:47:00.315056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f02cf4884e'
down_revision = 'deb62770d2cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('renter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('facebook_username', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('renter', schema=None) as batch_op:
        batch_op.drop_column('facebook_username')
        batch_op.drop_column('google_username')

    # ### end Alembic commands ###
