"""add email verification to owner

Revision ID: add_email_verification_to_owner
Revises: add_enhanced_pricing_structure
Create Date: 2025-07-10 14:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_email_verification_to_owner'
down_revision = 'add_enhanced_pricing_structure'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner', sa.Column('email_verified', sa.Boolean(), nullable=True, default=False))
    op.add_column('owner', sa.Column('first_login', sa.Boolean(), nullable=True, default=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owner', 'first_login')
    op.drop_column('owner', 'email_verified')
    # ### end Alembic commands ### 