"""Add payment and payment_config tables

Revision ID: add_payment_tables
Revises: 89f02cf4884e
Create Date: 2025-01-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_payment_tables'
down_revision = '89f02cf4884e'
branch_labels = None
depends_on = None


def upgrade():
    # Drop payment table nếu đã tồn tại
    try:
        op.drop_table('payment')
    except Exception:
        pass
    # Drop payment_config table nếu đã tồn tại
    try:
        op.drop_table('payment_config')
    except Exception:
        pass
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create payment_config table
    op.create_table('payment_config',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.Column('payos_client_id', sa.String(length=100), nullable=False),
        sa.Column('payos_api_key', sa.String(length=200), nullable=False),
        sa.Column('payos_checksum_key', sa.String(length=200), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('owner_id')
    )
    
    # Create payment table
    op.create_table('payment',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('payment_code', sa.String(length=100), nullable=False),
        sa.Column('order_code', sa.String(length=100), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('currency', sa.String(length=10), nullable=True),
        sa.Column('payos_transaction_id', sa.String(length=100), nullable=True),
        sa.Column('payos_signature', sa.String(length=500), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('payment_method', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('paid_at', sa.DateTime(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('customer_name', sa.String(length=100), nullable=True),
        sa.Column('customer_email', sa.String(length=120), nullable=True),
        sa.Column('customer_phone', sa.String(length=20), nullable=True),
        sa.Column('booking_id', sa.Integer(), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.Column('renter_id', sa.Integer(), nullable=False),
        sa.Column('checkout_url', sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
        sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ),
        sa.ForeignKeyConstraint(['renter_id'], ['renter.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('payment_code'),
        sa.UniqueConstraint('order_code')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop payment table
    op.drop_table('payment')
    
    # Drop payment_config table
    op.drop_table('payment_config')
    
    # ### end Alembic commands ### 