"""Remove CCCD image columns and add is_active column

Revision ID: e0719704fc80
Revises: 
Create Date: 2025-06-02 10:31:36.095407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0719704fc80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.drop_column('temp_role')
        batch_op.drop_column('cccd_front_image')
        batch_op.drop_column('cccd_back_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cccd_back_image', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('cccd_front_image', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('temp_role', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
